{% set major_minor = "5.15" %}
{% set version = major_minor + ".3" %}

package:
  name: qtlocation
  version: {{ version }}

source:
  url: http://download.qt.io/official_releases/qt/{{ major_minor }}/{{ version }}/submodules/qtlocation-everywhere-opensource-src-{{ version }}.tar.xz
  sha256: a69f28ccfd4ef8e69e0131b178d41d71264be836f2f55bd29731e908a22c6bbd

build:
  number: 0
  # workaround issues with qt
  merge_build_host: True   # [linux]

requirements:
  build:
    - perl
    - jom  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # The CDT packages below are those used in qt-feedstock
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - qt-main {{ version }}
  run:
    - qt-main {{ version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libQt5Location${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libQt5Positioning${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\Qt5Location_conda.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\Qt5Positioning_conda.dll exit 1  # [win]

about:
  home: http://qt-project.org
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE.LGPLv3
  summary: 'Use spatial data and information services in Qt'
  description: |
      The Qt Location API helps you create viable mapping solutions using
      the data available from some of the popular location services.
  doc_url: https://doc.qt.io/qt-5.6/qtlocation-index.html
  dev_url: https://github.com/qt/qtlocation

extra:
  recipe-maintainers:
    - ceholden
    - gillins
