{% set name = "qtlocation" %}
{% set version = "5.6.2" %}
{% set sha256 = "b153a4ab39f85d801699fe8adfa9e36496ecb392d2ded3c28e68a74b1c50e8d8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://download.qt.io/official_releases/qt/5.6/{{ version }}/submodules/qtlocation-opensource-src-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # Skip py35 since py36 is built and uses same vc14
  number: 2

requirements:
  build:
    - perl  # avoid making a matrix of perl builds
    - jom  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - qt
  run:
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libQt5Location.so  # [linux]
    - test -f ${PREFIX}/lib/libQt5Positioning.so  # [linux]
    - test -f ${PREFIX}/lib/libQt5Location.dylib  # [osx]
    - test -f ${PREFIX}/lib/libQt5Positioning.dylib  # [osx]
    - if not exist %LIBRARY_BIN%\\Qt5Location.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\Qt5Positioning.dll exit 1  # [win]

about:
  home: http://qt-project.org
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE.LGPLv3
  summary: 'Use spatial data and information services in Qt'
  description: |
      The Qt Location API helps you create viable mapping solutions using
      the data available from some of the popular location services.
  doc_url: https://doc.qt.io/qt-5.6/qtlocation-index.html
  dev_url: https://github.com/qt/qtlocation

extra:
  recipe-maintainers:
    - ceholden
