# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Y/sm6InPMHwtx1TzFHX2Tj6xvdjyqk69k0XbIzBs1fSGwxtgfaAH0WaNd/i3J2eGa6Pzlz0LodC0hOxWP7Eah4HEoYG+68IBKnopQmiXfDtUQe5zROlATcBA8WjIVJkLlqWqWhCtcrUY70lezWb527i6rCLRqdWT+0llOv67Y57Gle6ZBTFzO/hQzXDT48qEbVIeebht3A9aq8wYT3xrPkNvizws2ch2hGoc+Yigmh4OcxSu+b1PVp/AOrLSEAI0xOeqzxvEzhugaueG0IeCb2XfYFHCnMCCKFuRdLxVlgdYBnIt3SvY6Gda/4OEiPLhHYINRdhS8yDf9i+fjqWsXnWeFMoMaULnMPo6tTNac1BEVKe3/9uy0r6eLgc1TSQypl3vAQHk/uo0zGn6f+oE5qr51RtnLf1OL4yZjYHQ3calMKrTZc+oWd9Dc5Ca6IyFY7BnKHnLCEg7106uAWAo3R5ihngA9LrWWkPdA/o6qgA5eQbRwp8g1MZGGPveFfSShTZFY+3kC205sSd8CK9bKTUUsb+iLwCidZhA+x5yUvDqlVKAjL+kadu8AmjMTMGbJNYbS8f5ob3HDQwMB7qNhwvkijLgqW0WE1e2h1JPFHUEz2rEjzp9QVHoZCaNF3C2blI48DykNIHwWAZL1egINi+gbNwyUl3JUaYWO4dFZtg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml