compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '34'
provider:
  osx: azure
  linux: azure
  win: azure
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
