travis:
  secure:
    BINSTAR_TOKEN: Y/sm6InPMHwtx1TzFHX2Tj6xvdjyqk69k0XbIzBs1fSGwxtgfaAH0WaNd/i3J2eGa6Pzlz0LodC0hOxWP7Eah4HEoYG+68IBKnopQmiXfDtUQe5zROlATcBA8WjIVJkLlqWqWhCtcrUY70lezWb527i6rCLRqdWT+0llOv67Y57Gle6ZBTFzO/hQzXDT48qEbVIeebht3A9aq8wYT3xrPkNvizws2ch2hGoc+Yigmh4OcxSu+b1PVp/AOrLSEAI0xOeqzxvEzhugaueG0IeCb2XfYFHCnMCCKFuRdLxVlgdYBnIt3SvY6Gda/4OEiPLhHYINRdhS8yDf9i+fjqWsXnWeFMoMaULnMPo6tTNac1BEVKe3/9uy0r6eLgc1TSQypl3vAQHk/uo0zGn6f+oE5qr51RtnLf1OL4yZjYHQ3calMKrTZc+oWd9Dc5Ca6IyFY7BnKHnLCEg7106uAWAo3R5ihngA9LrWWkPdA/o6qgA5eQbRwp8g1MZGGPveFfSShTZFY+3kC205sSd8CK9bKTUUsb+iLwCidZhA+x5yUvDqlVKAjL+kadu8AmjMTMGbJNYbS8f5ob3HDQwMB7qNhwvkijLgqW0WE1e2h1JPFHUEz2rEjzp9QVHoZCaNF3C2blI48DykNIHwWAZL1egINi+gbNwyUl3JUaYWO4dFZtg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
compiler_stack: comp7
max_py_ver: "37"
max_r_ver: "34"
provider:
  osx: azure
  linux: azure
  win: azure